FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["SimpleNumber.Api.csproj", "./"]
RUN dotnet restore "SimpleNumber.Api.csproj"
COPY . .
RUN dotnet publish "SimpleNumber.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV APSNETCORE_URLS=http://+:8080
ENTRYPOINT [ "dotnet", "SimpleNumber.Api.dll" ]